[project]
name = "decentralized-cloud-storage"
authors = ["goodnews akpan"]
description = ""
telemetry = true
requirements = []
[contracts.decentralized-cloud-storage]
path = "contracts/decentralized-cloud-storage.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
